spring:
  application:
    name: insurance-service
  datasource:
    url: jdbc:postgresql://insurance-db:5432/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

dekorate:
  openshift:
    auto-deploy-enabled: true
    #    deployment-kind: Deployment
    replicas: 2
    expose: true
    env-vars:
      - name: DATABASE_USER
        value: database-user
        secret: person-db
      - name: DATABASE_PASSWORD
        value: database-password
        secret: person-db
      - name: DATABASE_NAME
        value: database-name
        secret: person-db
  s2i:
    enable: true
    auto-deploy-enabled: true